### ISSUE TITLE
不太明白

### ISSUE THREAD

**Issue by zachapda** [ChiyukiRuon/KawaiChiyuki_bot#2]
这个咋用（

**Comment by ChiyukiRuon** [comment]
这是一个Telegram机器人，你可以在Telegram里搜索KawaiChiyuki_bot来找到她，或者直接点击https://t.me/KawaiChiyuki_bot 来开始使用。
在聊天框中输入/或者点击Menu按钮来查看并使用机器人支持的指令

**Comment by zachapda** [comment]
Telegram是啥（

**Comment by ChiyukiRuon** [comment]
这边建议百度一下（
